### ISSUE TITLE
optional mathematical delimiter

### ISSUE THREAD

**Issue by YerKoV** [RyotaUshio/obsidian-math-booster#174]
I would like to ask you a question, is there a way to change the mathematical delimiter of the dollar $ to \(...\) ? I am looking for a long time for this.

**Comment by RyotaUshio** [comment]
Sorry, but probably I can't help you about this. I've ever seen several people talking about it, but none of them seemed to have a good luck.

At first, I thought it would be possible if we could somehow modify the MathJax configuration file. But it seems not so simply according to this post (I'm not sure how correct it is though)

https://forum.obsidian.md/t/expose-mathjax-configuration-file/3701/5

So I have no particular solution for this problem.
It would be possible to make a plugin that mimics `$...$` by `\(...\)` using the CodeMirror decorations and text replacement, it would be only a hacky workaround.
