### ISSUE TITLE
Rewrite indexing machanism using web workers

### ISSUE THREAD

**Issue by RyotaUshio** [RyotaUshio/obsidian-math-booster#177]
Currently, Math Booster needs much more time to finish the [initial indexing](https://github.com/RyotaUshio/obsidian-math-booster/blob/ac37c91c92a857a2c91c2807c667a9c96016c746/src/main.ts#L60-L76) than Dataview does.

The current implementation is pretty naive. Using web workers (which Dataview does) might improve the performance.

https://github.com/blacksmithgu/obsidian-dataview/tree/master/src/data-index

(Correct me if I'm saying something dumb)

**Comment by joelatschool** [comment]
I think this should be prioritized; I have a rather large and complex vault, and Math Booster currently interferes so much with its initialization that Obsidian ends up unresponsive for several minutes. I really like it and I tend to work for long sessions so I usually suffer through, but there's gotta be a better way.

**Comment by RyotaUshio** [comment]
Work in progress: learning from [Datacore](https://github.com/blacksmithgu/datacore)

**Comment by RyotaUshio** [comment]
Alpha-released in [2.0.0-alpha](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.0.0-alpha)

**Comment by RyotaUshio** [comment]
Hey @joelatschool, I've released it as [2.0.0-beta](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.0.0-beta). It's not on the community plugin browser inside Obsidian, but you can [install it via BRAT](https://github.com/RyotaUshio/obsidian-math-booster#installation).

Does this solve your problem? If not, feel free to reopen this issue!
