### ISSUE TITLE
Collapsible Theorem Callout

### ISSUE THREAD

**Issue by peterc-s** [RyotaUshio/obsidian-math-booster#183]
Thanks for the awesome plugin, really liking it other than one thing; when I used to take notes without the plugin I quite liked that I could collapse headings made with markdown to remove clutter. Would it be possible to implement a similar way to collapse theorem callouts so that it shows just the type of callout, number, and name?

I know this is a thing with proof environments (#138).

**Comment by RyotaUshio** [comment]
Hi, thanks for the idea!

Fortunately, it will be very easy to implement it unline the case of proofs!
In fact, I didn't add the option because I thought no one would want to fold a theorem when I wrote this plugin, which turned out to be false now😜

I will implement this feature before long!

**Comment by RyotaUshio** [comment]
Alpha-released in [2.0.0-alpha](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.0.0-alpha).

You can manually type, for example, 
```
> [!theorem]+
> Hello
```
or alternatively, use `Insert theorem callout` command.

**Comment by Diane-Best** [comment]
Would it be possible to implement a similar way to collapse proof environment? Sometimes, the proof are too long you know.
