### ISSUE TITLE
2.0.0-beta4 clobbers preexisting definition callouts

### ISSUE THREAD

**Issue by joelatschool** [RyotaUshio/obsidian-math-booster#193]
I'm not sure if this counts as a bug so much as its arguably a design/defaults issues. My vault already was structured around theorem/definition callouts before using this plugin and so I have a lot of notes that have just one callout, which is either a theorem or a definition, usually without any customization (so like 
```md
>[!definition]
> Blah Blah Blah
```
). When I turn on the "If a note only has one theorem callout, set it as main" setting, as these are recognized as main callouts, and so they end up causing lots of links to notes to show up as "Definition 1" or "Theorem 1" instead of something more descriptive:
![image](https://github.com/RyotaUshio/obsidian-math-booster/assets/94202132/242e0ec4-1b23-4f04-b036-90093c348380)

Logically I think every individual part of how this works makes sense (unless there's a bug somewhere I'm missing), but I don't think the outcome is very logical. IMO, the best way to resolve this would be to make it so that `auto` numbered theorem callouts that are the only theorem callout in a note are unnumbered and either implicitly name them according to the note they are in, or special-case that when an unnamed theorem callout is the main callout in a note, it does not get set as the mathLink.

**Comment by RyotaUshio** [comment]
Hi, I really appreciate a lof of helpful feedback from you!

> special-case that when an unnamed theorem callout is the main callout in a note, it does not get set as the mathLink.

I found this option the most appealing, so I implemented it as the new "Ignore a "main" theorem callout without its own title" option. (Available as [2.0.0-beta11](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.0.0-beta11))

Also, this issue helped me notice some related bugs. For example, the "Note mathLink format" setting wasn't working after rewriting the indexing part when I updated this plugin to 2.0.0-*.

Again, thank you a lot for your help! Feel free to reopen this issue if you have further suggestions.
