### ISSUE TITLE
Cannot import plugin to Obsidian because of incomplete release

### ISSUE THREAD

**Issue by NekomaShu** [RyotaUshio/obsidian-math-booster#201]
When I go to import the plugin through BRAT, Obsidian throws the following error:

"RyotaUshio/obsidian-math-booster
The release is not complete and cannot be downloaded. main.js is missing from the Release."

And fixes to this issue? I can load the 1.0.4 plugin via the frozen release option in BRAT, but not the latest one. Any help is appreciated.

![image](https://github.com/RyotaUshio/obsidian-math-booster/assets/130188252/bf43cbab-5704-443a-a9c4-b3ad830d1050)

**Comment by RyotaUshio** [comment]
Thanks for reporting. This is my fault, because I updated `manifest-beta.json` (which BRAT uses to determine what version to install) but have not actually made the corresponding release yet. Hold on for a minute!

**Comment by RyotaUshio** [comment]
Now you will be able to install the latest version, `2.0.0-beta-9`! Thanks for reporting.

**Comment by NekomaShu** [comment]
Thanks a lot! That worked like a charm!!
