### ISSUE TITLE
[feature request] Include a setting that would automatically number all equations, even if not explicitly referenced.

### ISSUE THREAD

**Issue by r-curry** [RyotaUshio/obsidian-math-booster#209]
I think this would make doing physics/math work much easier and more pain free on Obsidian.

**Comment by RyotaUshio** [comment]
Actually, that's easier to implement than numbering only referenced ones. I will include it in a future release.

**Comment by r-curry** [comment]
That is actually amazing. Thank you so much!

**Comment by RyotaUshio** [comment]
Released in [2.1.0](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.1.0)!
